package com.zyq.myemptyproject.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Fri Mar 22 16:46:41 CST 2019.</p>
 *
 * @author zhangyq
 */
@Entity
@Table(name = "menu_permission_relation")
public class Menu_Permission_Relation implements Serializable {


    private static final long serialVersionUID = 4920373248224435403L;


    /**
     * 关联关系id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * 权限ID
     */
    @Column(name = "permission_id")
    private Long permissionId;

    /**
     * 角色ID
     */
    @Column(name = "menu_id")
    private Long menuId;

    /**
     * 创建时间
     */
    @Column(name = "gmt_create_time")
    private Date gmtCreateTime;

    /**
     * 更新时间
     */
    @Column(name = "gmt_update_time")
    private Date gmtUpdateTime;

    public Menu_Permission_Relation() {
        super();
    }

    public Menu_Permission_Relation(Long id, Long permissionId, Long menuId, Date gmtCreateTime, Date gmtUpdateTime) {
        this.id = id;
        this.permissionId = permissionId;
        this.menuId = menuId;
        this.gmtCreateTime = gmtCreateTime;
        this.gmtUpdateTime = gmtUpdateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    public Long getMenuId() {
        return this.menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public Date getGmtCreateTime() {
        return this.gmtCreateTime;
    }

    public void setGmtCreateTime(Date gmtCreateTime) {
        this.gmtCreateTime = gmtCreateTime;
    }

    public Date getGmtUpdateTime() {
        return this.gmtUpdateTime;
    }

    public void setGmtUpdateTime(Date gmtUpdateTime) {
        this.gmtUpdateTime = gmtUpdateTime;
    }

}
