package com.zyq.myemptyproject.entity;

import org.hibernate.annotations.JoinColumnOrFormula;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Fri Mar 22 16:46:41 CST 2019.</p>
 *
 * @author zhangyq
 */
@Entity
@Table(name = "sys_user")
public class User implements Serializable {


    private static final long serialVersionUID = 8810526111556654060L;


    /**
     * 用户ID
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long id;

    /**
     * 用户姓名
     */
    @Column(name = "user_name")
    private String userName;

    /**
     * 登陆账号
     */
    @Column(name = "login_name")
    private String loginName;

    /**
     * 登陆密码
     */
    @Column(name = "password")
    private String password;

    /**
     * 手机号
     */
    @Column(name = "phone")
    private String phone;

    /**
     * 邮箱
     */
    @Column(name = "mail")
    private String mail;

    /**
     * 创建时间
     */
    @Column(name = "gmt_create_time")
    private Date gmtCreateTime;

    /**
     * 最后登陆时间
     */
    @Column(name = "last_login_time")
    private Date lastLoginTime;
    /**
     * 错误登录次数
     */
    @Column(name = "error_login_number")
    private Integer errorLoginNumber;

    /**
     * 锁定状态 0：未锁定 1：锁定
     */
    @Column(name = "locked")
    private Integer locked;

    /**
     * 更新时间
     */
    @Column(name = "gmt_update_time")
    private Date gmtUpdateTime;
    /**
     * 删除标志 0：未删除 1：删除
     */
    @Column(name = "is_delete")
    private Integer deleted;

    public User() {
        super();
    }

    public User(String userName, String loginName, String password, String phone, String mail, Date gmtCreateTime, Date lastLoginTime, Integer errorLoginNumber, Integer locked, Date gmtUpdateTime, Integer deleted) {
        this.userName = userName;
        this.loginName = loginName;
        this.password = password;
        this.phone = phone;
        this.mail = mail;
        this.gmtCreateTime = gmtCreateTime;
        this.lastLoginTime = lastLoginTime;
        this.errorLoginNumber = errorLoginNumber;
        this.locked = locked;
        this.gmtUpdateTime = gmtUpdateTime;
        this.deleted = deleted;
    }

    /**
     * 存入session的构造函数
     *
     * @param userName
     * @param loginName
     * @param phone
     * @param mail
     * @param locked
     */
    public User(String userName, String loginName, String phone, String mail, Integer locked) {
        this.userName = userName;
        this.loginName = loginName;
        this.phone = phone;
        this.mail = mail;
        this.locked = locked;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Temporal(TemporalType.TIMESTAMP)
    public Date getGmtCreateTime() {
        return this.gmtCreateTime;
    }

    public void setGmtCreateTime(Date gmtCreateTime) {
        this.gmtCreateTime = gmtCreateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public Integer getLocked() {
        return this.locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    @Temporal(TemporalType.TIMESTAMP)
    public Date getGmtUpdateTime() {
        return this.gmtUpdateTime;
    }

    public void setGmtUpdateTime(Date gmtUpdateTime) {
        this.gmtUpdateTime = gmtUpdateTime;
    }

    public Integer getErrorLoginNumber() {
        return errorLoginNumber;
    }

    public void setErrorLoginNumber(Integer errorLoginNumber) {
        this.errorLoginNumber = errorLoginNumber;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

}
